frr defaults traditional
hostname R1
service integrated-vtysh-config
log stdout

router ospf
 ospf router-id 1.1.1.1
 network 100.10.10.0/29 area 0
 network 192.168.10.0/24 area 0
 default-information originate

line vty